# Generated by Django 6.0 on 2026-01-06 17:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('owner', 'Property Owner'), ('seeker', 'Property Seeker'), ('admin', 'Administrator')], default='seeker', help_text='Designates whether the user is a property owner or seeker.', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be in E.164 format (e.g., +919876543210).', regex='^\\+[1-9]\\d{1,14}$')])),
                ('profile_picture', models.ImageField(blank=True, help_text="User's profile photo.", null=True, upload_to='profile_pics/')),
                ('is_verified_owner', models.BooleanField(default=False, help_text='Indicates if the owner has passed manual verification.')),
                ('verification_document', models.FileField(blank=True, help_text="Owner's document for verification.", null=True, upload_to='verification_docs/')),
                ('verification_request_date', models.DateTimeField(blank=True, help_text='Date owner requested verification.', null=True)),
                ('flagged_by_system', models.BooleanField(default=False, help_text='Flagged by system for potential broker activity.')),
                ('flagged_reason', models.TextField(blank=True, help_text='Reason for system flagging.', null=True)),
                ('flagging_date', models.DateTimeField(blank=True, help_text='Date when system flagged the user.', null=True)),
                ('active_listings_count', models.PositiveIntegerField(default=0, help_text='Number of active properties listed by this owner.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_activity', models.DateTimeField(blank=True, help_text='Timestamp of last successful login.', null=True)),
                ('account_suspended', models.BooleanField(default=False, help_text="Is the user's account temporarily or permanently suspended?")),
                ('suspension_reason', models.TextField(blank=True, help_text='Reason for account suspension.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
