# Generated by Django 6.0 on 2026-01-06 18:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome or Heroicon class name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(help_text='e.g. Spacious 2BHK in Indiranagar near Metro', max_length=255)),
                ('description', models.TextField(help_text='Describe the property details, nearby landmarks, rules, etc.')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('independent', 'Independent House/Villa'), ('gated_community', 'Gated Community Villa'), ('pg', 'Paying Guest (PG)'), ('studio', 'Studio Apartment')], max_length=20)),
                ('bhk_type', models.CharField(blank=True, choices=[('1rk', '1 RK'), ('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('4plus', '5+ BHK')], max_length=10, null=True)),
                ('furnishing_status', models.CharField(choices=[('fully', 'Fully Furnished'), ('semi', 'Semi Furnished'), ('none', 'Unfurnished')], max_length=10)),
                ('preferred_tenants', models.CharField(choices=[('all', 'Any'), ('family', 'Family Only'), ('bachelor', 'Bachelor (Men)'), ('spinster', 'Bachelor (Women)'), ('company', 'Company Lease')], default='all', max_length=15)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(500)])),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, help_text='0 if included in rent', max_digits=8)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('locality', models.CharField(help_text='e.g. Koramangala, Whitefield', max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(default='Karnataka', max_length=50)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.MinValueValidator('100000')])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('available_from', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('rented', 'Rented Out'), ('archived', 'Archived (Deleted)'), ('flagged', 'Flagged (Broker Suspected)')], default='active', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Switch to toggle visibility instantly')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='listings.amenity')),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False, help_text='This image will be shown on the listing card.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.property')),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'locality'], name='listings_pr_city_694d81_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rent_amount'], name='listings_pr_rent_am_b76b72_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bhk_type'], name='listings_pr_bhk_typ_1364e1_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='listings_pr_status_de90a3_idx'),
        ),
    ]
