# Generated by Django 6.0.3 on 2026-03-11 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3+')], null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='builtup_area',
            field=models.PositiveIntegerField(blank=True, help_text='Built-up area in sq. ft.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.CharField(blank=True, choices=[('ground', 'Ground Floor'), ('1_3', '1 to 3'), ('4_6', '4 to 6'), ('7_9', '7 to 9'), ('10_plus', '10 & above')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking_2w',
            field=models.BooleanField(default=False, help_text='2-wheeler parking available'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking_4w',
            field=models.BooleanField(default=False, help_text='4-wheeler parking available'),
        ),
        migrations.AddField(
            model_name='property',
            name='non_veg_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_age',
            field=models.CharField(blank=True, choices=[('lt1', 'Less than 1 year'), ('lt3', 'Less than 3 years'), ('lt5', 'Less than 5 years'), ('lt10', 'Less than 10 years'), ('gt10', 'Over 10 years')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total floors in the building', null=True),
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. '2BHK in Pune below 25k'", max_length=120)),
                ('query_string', models.TextField(help_text='Raw URL query string, e.g. bhk=2bhk&city=pune&rent_max=25000')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved Searches',
                'ordering': ['-created_at'],
            },
        ),
    ]
